[package]
name = "yet-another-chip-8-emulator"
version = "0.1.0"
edition = "2021"
# build = "build.rs"

[features]
default = []
# use_sdl2_mac_framework = ["sdl2/use_mac_framework"]

[dependencies]
rand = "0.8.5"
# sdl2 = "0.35.2"

[profile.dev]
overflow-checks = false
