[package]
name = "mchip8"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8.4", features = ["alloc", "small_rng"], default-features = false }

[profile.dev]
overflow-checks = false
